# Generated by Django 2.2.3 on 2019-08-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='Permissive_to_post',
            field=models.BooleanField(default=False),
        ),
    ]
